var FILE_NAME_TO_FRAGMENT_NAME={
"seizetheDJ.html":"seize the DJ",
"1955.html":"1955",
"actionandpassion.html":"Action and Passion",
"abeginning.html":"a beginning",
"command_3.html":"command",
"eddornseyes.html":"Ed Dorn's eyes",
"-30-.html":"-30-",
"4annam.html":"4. Anna M.",
"waterglinting.html":"water glinting",
"Chryalis.html":"Chryalis",
"Whosthestoolie.html":"Who's the stoolie?",
"15.html":"15",
"springsprung.html":"spring sprung",
"somesay.html":"some say",
"A_.html":"A",
"Observatory.html":"Observatory",
"wisdom.html":"wisdom",
"apoetafloat.html":"A poet, afloat",
"whereweeblong.html":"where we eblong",
"concealedbirds.html":"concealed birds",
"tempsvierge.html":"temps vierge",
"shadowhappiness.html":"shadow happiness",
"myfathersroom.html":"my father's room",
"birdsweave.html":"birds weave",
"KeyWest.html":"Key West",
"22shortfilmsrerpower.html":"22short films re R Power",
"SEEside.html":"SEE side",
"Itistothee.html":"It is to thee...",
"Father.html":"Father",
"bazaar.html":"bazaar",
"hj.html":">H&J",
"heprotesteth.html":"he protesteth",
"weoftenfelt.html":"We often felt",
"whosaidwhat.html":"who said what",
"lights.html":"lights",
"4AnnaM.html":"4. Anna M.",
"mother.html":"mother",
"Byitscover.html":"By its cover",
"nuclearfishing.html":"nuclear fishing",
"readingstoryspaces.html":"Reading Storyspaces [excerpt from the original instructions from 1996 Storyspace edition]",
"glennbarrett.html":"Glenn Barrett",
"Riddle.html":"Riddle",
"michaelcentury.html":"Michael Century",
"severity.html":"severity",
"HousaHoser.html":"Housa Hoser",
"whathappens.html":"what happens",
"huh.html":"huh?",
"PleasantLake.html":"Pleasant Lake",
"asasillyman.html":"as a silly man.",
"WolfLake.html":"Wolf Lake",
"outerspace.html":"outer space",
"allhumanwisdom.html":"all human wisdom",
"5Worldsedge.html":"5. World's edge",
"myself.html":"myself",
"intimenightall.html":"in time, night, all",
"howhesleeps.html":"how he sleeps",
"drowsy.html":"drowsy",
"vivailpapa.html":"Viva il papa",
"PandoraLaura.html":"Pandora Laura",
"q.html":"Q",
"caught.html":"caught",
"LittleGedditing.html":"Little Gedditing",
"Chronicle.html":"Chronicle",
"LaundrydoneBeautiful.html":"Laundry done. Beautiful",
"who.html":"...who",
"reignsinadrytime.html":"reigns in a dry time",
"freewill.html":"free will",
"history.html":"History",
"Itbeginssomewhere.html":"It begins somewhere",
"Blueboat-city.html":"Blue boat-city",
"Sleepy.html":"Sleepy",
"che.html":"Che",
"towersinair.html":"towers in air",
"songs.html":"Songs",
"A.html":"A",
"input.html":"input",
"Roundususuallsuspects.html":"Round us, usuall suspects",
"freshessai.html":"Fresh essai",
"aphoto.html":"a photo",
"reineofhearts.html":"Reine of hearts",
"secondekphrastic.html":"second ekphrastic",
"ourstorysofar.html":"our story so far",
"protector.html":"protector",
"Ohbravenewworld.html":"Oh brave new world",
"6.html":"6",
"Cixous.html":"Cixous",
"inthehigherair.html":"in the higher air",
"postcardtoher.html":"postcard to her",
"manofaction.html":"man of action",
"outofmemory.html":"out of memory",
"hewakes.html":"he wakes",
"Boytake.html":"Boy take?",
"chryalis.html":"Chryalis",
"Che.html":"Che",
"11.html":"11",
"Heights.html":"Heights",
"scrimshaw.html":"Scrimshaw",
"garments.html":"garments",
"Iknownotsees.html":"I know not see's",
"LaCrise.html":"La Crise",
"outofrhythm.html":"out of rhythm",
"littlegedditing.html":"Little Gedditing",
"prophet.html":"prophet",
"versusthetermination.html":"versus the termination",
"theend.html":"the end",
"etcheditself.html":"etched itself",
"HJ.html":">H&J",
"tapes56.html":"Tapes 5&6",
"twom.html":"Two m",
"seizethedj.html":"seize the DJ",
"thesailorread.html":"The Sailor read",
"butter.html":"Butter",
"servicemarks.html":"service marks",
"Everyonetriesnottobe.html":"Everyones tries not to be",
"river.html":"River",
"workplay.html":"work play",
"FredandBarney.html":"Fred and Barney",
"centmilledefacts.html":"Cent mille de facts",
"2Timesgeometry.html":"2. Time's geometry",
"5.html":"5",
"riddle.html":"Riddle",
"MichaelCentury.html":"Michael Century",
"gs.html":"g's",
"chronicle.html":"Chronicle",
"courses.html":"courses",
"FrancoisGirards.html":"Francois Girard's",
"aleagueofnations.html":"a League of Nations",
"genesis.html":"Genesis?",
"Heatwavechangeofpace.html":"Heat wave:change of pace",
"cixous.html":"Cixous",
"fourhorsemen.html":"four horsemen",
"operatingsystem.html":"operating system",
"Protagonistes.html":"Protagonistes",
"anaside.html":"an aside",
"asinisteract.html":"a sinister act",
"Twom.html":"Two m",
"node.html":"node",
"takenbythecontinual.html":"taken by the continual",
"1.html":"1",
"command_2.html":"command",
"biomass.html":"biomass",
"six.html":"six",
"dateline.html":"dateline:",
"a.html":"@",
"roundususuallsuspects.html":"Round us, usuall suspects",
"endone.html":"end one",
"adeath.html":"A: death",
"Centmilledefacts.html":"Cent mille de facts",
"elOrGua.html":"el OrGua",
"sosinkstheday-star.html":"So sinks the day-star",
"Freshessai.html":"Fresh essai",
"riding.html":"riding",
"somefalseleads.html":"some false leads",
"Notes.html":"Notes",
"spelt.html":"spelt",
"howthingshappen-guns.html":"how things happen-guns",
"EnglishtextbyBruce.html":"English text by Bruce",
"Aspittinimage.html":"A spittin im age",
"tegvara.html":"tegvara",
"3.html":"3",
"thirdekphrastic.html":"third ekphrastic",
"ikons.html":"ikons",
"Cosifantutte.html":"Cosi fan tutte",
"hi-pitchedvoices.html":"Hi-Pitched Voices",
"6continental.html":"6. Continental",
"after.html":"after",
"Daniel.html":"Daniel",
"TheSailorread.html":"The Sailor read",
"eveningstar.html":"Evening Star",
"command003.html":"command",
"surrender.html":"surrender",
"damndearbloombloor.html":"damn/dear? Bloom/Bloor?",
"daniel.html":"Daniel",
"occidental.html":"occidental",
"Mars.html":"Mars",
"whosthestoolie.html":"Who's the stoolie?",
"Themeaning.html":"The meaning",
"nightswork.html":"night's work",
"duringthehypertext198.html":"during the Hypertext 1989",
"Scrimshawsalibi.html":"Scrimshaw's alibi",
"theendofthecoldwar.html":"The End of the Cold War",
"Idyllicthey.html":"Idyllic, they",
"DaniChe.html":"DaniChe",
"alaxalasalass.html":"A lax, alas, a lass",
"fidelity.html":"fidelity",
"SoIwroteacolumn.html":"So I wrote a column.",
"andwatson.html":"and Wat, son?",
"theoldmanandthesee.html":"The Old Man and the see",
"crossexamination.html":"Cross Examination",
"father.html":"Father",
"Hestirs-Obie.html":"He stirs-Obie",
"1CalliopeatMarathon.html":"1. Calliope at Marathon",
"DoesHenrysee.html":"Does Henry see?",
"caring.html":"caring",
"Scrimshaw.html":"Scrimshaw",
"command.html":"command.",
"worldnoises.html":"world noises",
"ListaLinkow.html":"ListaLinkow",
"Thekindofmanwho.html":"The kind of man who",
"ja.html":"Ja!",
"seas.html":"seas",
"suspicions.html":"suspicions",
"wonders.html":"wonders",
"credits.html":"Credits",
"memory.html":"memory",
"certaincertainties.html":"certain certainties",
"TheOldManandthesee.html":"The Old Man and the see",
"Times.html":"Times",
"3Johan.html":"3. Johan",
"caught--continued.html":"caught-- continued",
"savaissabrett.html":"Savais sabrett?",
"nousnote.html":"á nous note",
"ARiddleman.html":"A Riddleman",
"everyones.html":"everyone's",
"illegalthey.html":"illegal they",
"Lake-memory.html":"Lake-memory",
"wolflake.html":"Wolf Lake",
"hj2.html":">H&J",
"Meaning.html":"Meaning",
"Pasadena.html":"Pasadena",
"observatory.html":"Observatory",
"pasadena.html":"Pasadena",
"dazeofthewoke.html":"daze of the woke",
"lurchesfromitsmouth.html":"lurches from its mouth",
"livingstill.html":"living still",
"blue.html":"blue",
"hensandchicks.html":"hens and chicks",
"michael.html":"Michael",
"inlightonlight.html":"in light on light",
"damndearBloomBloor.html":"damn/dear? Bloom/Bloor?",
"tempofuggechetassonna.html":"tempo fugge che t'assonna",
"twilight.html":"twilight",
"son_2.html":"Son",
"justwheretheriver.html":"just where the river",
"Obieswathed.html":"Obie swathed",
"mars.html":"Mars",
"ReadingStoryspaces.html":"Reading Storyspaces",
"sleepysong.html":"sleepy song",
"portraitoftheartist.html":"portrait of the artist",
"Wheretheblacknesslaps.html":"Where the blackness laps",
"TheEndoftheColdWar.html":"The End of the Cold War",
"oreallyo.html":"o really o",
"8.html":"8",
"Dalaiinthesky.html":"Dalai in the sky",
"yourstruly.html":"yours, truly",
"lifeinabox.html":"life in a box",
"lesheurs.html":"Les Heurs",
"anescaperoute.html":"an escape route",
"seeside.html":"SEE side",
"byitscover.html":"By its cover",
"GhislaineGuertin.html":"Ghislaine Guertin",
"housahoser.html":"Housa Hoser",
"thekindofmanwho.html":"The kind of man who",
"themeaning.html":"The meaning",
"onpineneedles.html":"on pine needles",
"and.html":"and ...",
"__nousnote.html":"__ nous note",
"sorrows.html":"sorrows",
"alone.html":"alone",
"caughtagain.html":"caught (again)",
"saltorchopinin6.html":"salt or Chopin in 6",
"easewhybother.html":"ease, why bother?",
"Reineofhearts.html":"Reine of hearts",
"Prospects.html":"Prospects",
"Anchoringdevices.html":"Anchoring devices",
"editedout.html":"edited out",
"Phaedrus.html":"Phaedrus",
"lake-memory.html":"Lake-memory",
"meaning.html":"Meaning",
"elf.html":"elf",
"13.html":"13",
"notsomuch.html":"not so much",
"command_1.html":"command",
"suit.html":"suit",
"whether.html":"whether",
"whathappenedtous.html":"what happened. to. us.",
"failus.html":"fail us?",
"hishopes.html":"his hopes",
"suitcasememory.html":"suitcase memory",
"asylum.html":"asylum",
"echolalia.html":"echolalia",
"acallfrombelow.html":"a call from below",
"ems.html":"ems",
"tiredofpomo.html":"tired of pomo?",
"phaedrus.html":"Phaedrus",
"sam.html":"sam",
"saltorChopinin6.html":"salt or Chopin in 6",
"realm.html":"realm",
"Weoftenfelt.html":"We often felt",
"command004.html":"command",
"gnosis.html":"gnosis",
"pleasures.html":"pleasures",
"4.html":"4",
"asuspect.html":"a suspect!",
"eerjordan.html":"e'er Jordan",
"1982.html":"1982",
"query.html":"query",
"pleasantlake.html":"Pleasant Lake",
"aprilewaltera.html":"Aprile, Walter A",
"cosifantutte.html":"Cosi fan tutte",
"englishtextbybruce.html":"English text by Bruce",
"1calliopeatmarathon.html":"1. Calliope at Marathon",
".html":"*",
"noons.html":"noons",
"22shortfilmsreRPower.html":"22short films re R Power",
"looknow--obie.html":"Look now--Obie",
"awayout.html":"a way out",
"pandoralaura.html":"PandoraLaura",
"Songs.html":"Songs",
"motherlandfathertongue.html":"motherland fathertongue",
"toher-perspective.html":"to her-perspective",
"there.html":"there",
"prospects.html":"Prospects",
"hestirs-obie.html":"He stirs-Obie",
"couplet.html":"couplet",
"asiflightspoke.html":"as if light spoke",
"sonata.html":"(son)ata",
"Aswan.html":"A swan",
"blueboat-city.html":"Blue boat-city",
"iknownotsees.html":"I know not see's",
"wheretheblacknesslaps.html":"Where the blackness laps",
"Tapes56.html":"Tapes 5&6",
"command_002.html":"command",
"2timesgeometry.html":"2. Time's geometry",
"father_1.html":"Father",
"akeyquestion.html":"a key question",
"fourthekphrastic.html":"fourth ekphrastic",
"September.html":"September",
"aretreatingfigure.html":"a retreating figure",
"greyday.html":"grey day",
"command_001.html":"command",
"cave.html":"cave",
"immigranttothisshore.html":"immigrant to this shore",
"ideograms.html":"ideograms",
"EveningStar.html":"Evening Star",
"scrimshawsalibi.html":"Scrimshaw's alibi",
"naturaleloquence.html":"natural eloquence",
"fustytu.html":"fusty tu",
"repaying.html":"repaying",
"elorgua.html":"el OrGua",
"piano.html":"piano",
"firstekphrastic.html":"first ekphrastic",
"andWatson.html":"and Wat, son?",
"10.html":"10",
"CrossExamination.html":"Cross Examination",
"dateline_2.html":"dateline:",
"ghislaineguertin.html":"Ghislaine Guertin",
"shid.html":"shid",
"aLeagueofNations.html":"a League of Nations",
"interrogationinterra.html":"interrogation, in terra",
"couplet_1.html":"couplet",
"ActionandPassion.html":"Action and Passion",
"comingtowriting.html":"coming to writing",
"belowanoldmountain.html":"below an old mountain",
"obiesmouth-truth.html":"Obie's mouth-truth",
"Son_1.html":"Son",
"lettureimpalpabili.html":"letture impalpabili",
"Hi-PitchedVoices.html":"Hi-Pitched Voices",
"Passages.html":"Passages",
"modernmanandbaby.html":"modern man and baby",
"september.html":"September",
"__.html":"*",
"dautunno.html":"d'autunno",
"AprileWalterA.html":"Aprile, Walter A",
"goldbugs.html":"goldbugs",
"sometimesdawn.html":"sometimes dawn",
"History.html":"History",
"Genesis.html":"Genesis?",
"duringtheHypertext198.html":"during the Hypertext 198",
"command_1b.html":"command",
"Iwasntevenguiltyof.html":"I wasn't even guilty of",
"3johan.html":"3. Johan",
"laundrydonebeautiful.html":"Laundry done. Beautiful",
"eerJordan.html":"e'er Jordan",
"EdDornseyes.html":"Ed Dorn's eyes",
"inthedisclosuresof.html":"in the disclosures of",
"Newday.html":"New day.",
"archangel.html":"archangel",
"Son.html":"Son",
"keywest.html":"Key West",
"boytake.html":"Boy take?",
"twos.html":"twos",
"Son_2.html":"Son",
"son.html":"Son",
"anthem.html":"anthem",
"iceman.html":"ice man",
"ariddleman.html":"A Riddleman",
"justlikelife.html":"just like life",
"heights.html":"Heights",
"essencily.html":"essencily",
"transubstantiate.html":"transubstantiate",
"stepone.html":"step one",
"francoisgirards.html":"Francois Girard's",
"_.html":"...",
"14.html":"14",
"Butter.html":"Butter",
"apositiveid.html":"a positive ID!",
"River.html":"River",
"idyllicthey.html":"Idyllic, they",
"heaintheavy.html":"he ain't heavy",
"backstory.html":"backstory",
"anchoringdevices.html":"Anchoring devices",
"fredandbarney.html":"Fred and Barney",
"boat.html":"boat",
"inahalf-hiddencave.html":"in a half-hidden cave",
"oulipo.html":"oulipo",
"uponoppositeshores.html":"upon opposite shores",
"areporterreflects.html":"a reporter reflects",
"heatwavechangeofpace.html":"Heat wave:change of pace",
"6Continental.html":"6. Continental",
"MickHammer.html":"Mick Hammer",
"Ja.html":"Ja!",
"newday.html":"New day.",
"gettingitdown.html":"getting it down",
"morning.html":"morning",
"anotherhouse.html":"another house",
"two.html":"two",
"asong.html":"a song",
"parry.html":"parry",
"everyonetriesnottobe.html":"Everyone tries not to be",
"mouths-world.html":"mouths-world",
"aloversdiscourse.html":"a lovers' discourse",
"transmogrifikey.html":"transmogrifikey",
"12.html":"12",
"soiwroteacolumn.html":"So I wrote a column.",
"aswan.html":"A swan",
"Vivailpapa.html":"Viva il papa",
"ohbravenewworld.html":"Oh brave new world",
"dateline_1.html":"dateline:",
"Alaxalasalass.html":"A lax, alas, a lass",
"parable.html":"parable",
"times.html":"Times",
"rest-s.html":"rest-s",
"iwasntevenguiltyof.html":"I wasn't even guilty of",
"towhatend.html":"to what end?",
"leeryabandonnedchild.html":"leery, abandonned child",
"pianos.html":"pianos",
"mickhammer.html":"Mick Hammer",
"mechanicalquip.html":"mechanical quip",
"daniche.html":"DaniChe",
"protagonistes.html":"Protagonistes",
"whatthesailorsays.html":"what the sailor says",
"Sosinkstheday-star.html":"So sinks the day-star",
"courting.html":"courting",
"Adeath.html":"A: death",
"sweaters.html":"sweaters",
"Obiesmouth-truth.html":"Obie's mouth-truth",
"whetherreport.html":"whether report",
"electric.html":"electric",
"LesHeurs.html":"Les Heurs",
"seesee.html":"see see",
"ours.html":"ours",
"aspittinimage.html":"A spittin im age",
"stories.html":"stories",
"distanttenderness.html":"distant tenderness",
"whatsinkswhatrises.html":"what sinks, what rises",
"fiveelements.html":"five elements",
"nearly.html":"nearly",
"seaside.html":"seaside",
"inwhichhe.html":"in which he",
"autumnalwalkings.html":"autumnal walkings",
"thetruth.html":"the truth",
"eyes.html":"eyes",
"yoda.html":"yoda",
"7.html":"7",
"transformation.html":"transformation",
"itistothee.html":"It is to thee...",
"noonecared.html":"No one cared.",
"dickshunairy.html":"dick shun airy",
"phantom.html":"phantom",
"dialectic.html":"dialectic",
"son_1.html":"Son",
"Michael.html":"Michael",
"thiscomputer.html":"this computer",
"GlennBarrett.html":"Glenn Barrett",
"apositiveID.html":"a positive ID!",
"lacrise.html":"La Crise",
"justus.html":"just us",
"notes.html":"Notes",
"elkid.html":"el kid",
"fifthekphrastic.html":"fifth ekphrastic",
"Apoetafloat.html":"A poet, afloat",
"Looknow--Obie.html":"Look now--Obie",
"passages.html":"Passages",
"9.html":"9",
"720.html":"720",
"inpursuitofyo.html":"in pursuit of yo",
"partfour.html":"part four",
"5worldsedge.html":"5. World's edge",
"AERVER.html":"AER/VER",
"Savaissabrett.html":"Savais sabrett?",
"Father_1.html":"Father",
"totheleftof.html":"to the left of",
"here.html":"here",
"speech.html":"speech",
"Noonecared.html":"No one cared.",
"Q.html":"Q",
"andwhere.html":"and where",
"doeshenrysee.html":"Does Henry see?",
"soon.html":"soon",
"seven.html":"seven",
"multilingual.html":"multilingual",
"blacktalk.html":"black talk",
"sleepy.html":"Sleepy",
"2.html":"2",
"moredogons.html":"more dogons",
"dalaiinthesky.html":"Dalai in the sky",
"youllsees.html":"you'll sees",
"scent.html":"scent",
"itbeginssomewhere.html":"It begins somewhere",
"andshouldhavewonit.html":"and should have won it",
"obieswathed.html":"Obie swathed",
};


function htmlFileNameToFragmentName(x) {
    return FILE_NAME_TO_FRAGMENT_NAME[x];
}