class Guard{
	constructor(q,rev,title,txt){
		this.q=q;
	}
	
	q=null
	
}

var GUARDS  = {
	//"NAZWA.html":"tu idzie guard",

"__.html":"",
"_.html":"",
"yourstruly.html":"",
"youllsees.html":"v('livingstill') ? 1 : 0",
"yoda.html":"rl([0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333, 0.0333])",
"worldnoises.html":"",
"workplay.html":"v('greyday') ? 1 : 0",
"wonders.html":"(v('theend') && v('abeginning') ? 1 :  0)",
"wolflake.html":"(v('abeginning')) ? (v('reineofhearts') ? 0 : 1) : 2",
"wisdom.html":"(v('memory')) ? (v('gnosis') ? 0 : 2) : 1",
"whosthestoolie.html":"",
"whosaidwhat.html":"",
"who.html":"",
"whetherreport.html":"v('nousnote')  ? 1 : 0",
"whether.html":"",
"whereweeblong.html":"",
"wheretheblacknesslaps.html":"",
"whatthesailorsays.html":"",
"whatsinkswhatrises.html":"",
"whathappens.html":"",
"whathappenedtous.html":"",
"weoftenfelt.html":"v('waterglinting') ? (rl([0.2, 0.2, 0.2, 0.2, 0.2, 0.2])) : 0 ",
"waterglinting.html":"",
"vivailpapa.html":"",
"versusthetermination.html":"",
"uponoppositeshores.html":"",
"twos.html":"(v('scent') && v('sorrows') && !v('severity')) ? 0 : ((v('scent') && v('sorrows') && v('severity')) ? 2 : ((v('scent') && !v('suspicions') || !v('ssuit')) ? 1 : 2))",
"twom.html":"v('andwhere') ? 0 :  1",
"two.html":"",
"twilight.html":"",
"transubstantiate.html":"('seesee') ? 1 : 0",
"transmogrifikey.html":"",
"transformation.html":"(v('four') && v('riddle') && v('scent')) ? 2 : (v('four') && v('riddle') ? 1 : 0)",
"towhatend.html":"",
"towersinair.html":"(v('sonata') && v('Johan') && v('suit')) ? 0 : (v('HousaHoser') ? 1 : 2)",
"totheleftof.html":"",
"toher-perspective.html":"",
"tiredofpomo.html":"",
"times.html":"",
"thiscomputer.html":"('operatingsystem') ? 0 : 1",
"thirdekphrastic.html":"",
"thetruth.html":"",
"thesailorread.html":"",
"there.html":"(v('eyes') && !v('september')) ? 2 : (v('september') && v('eyes') && !v('songs') ? 3 : (v('caring') ? (v('firstekphrastic') ? 0 : 4) : 1))",
"theoldmanandthesee.html":"('seven') ? 1 : 0",
"themeaning.html":"",
"thekindofmanwho.html":"v('caught') ? 0 : 1",
"theendofthecoldwar.html":"",
"theend.html":"v('wonders') ? 0 : 1",
"tempsvierge.html":"v('couplet') ? 1 : 0",
"tempofuggechetassonna.html":"",
"tegvara.html":"",
"tapes56.html":"",
"takenbythecontinual.html":"v('butter') ? 1 : 0",
"sweaters.html":"v('actionandpassion') ? 0 : 1",
"suspicions.html":"v('speech') && v('suit') && v('boat') ? 0 : 1",
"surrender.html":"v('speech') && v('suit') && v('boat') ? 1 : 0",
"suitcasememory.html":"v('biomass') && !v('two') ? 1 : 0",
"suit.html":"v('speech') ? 0 : 1",
"stories.html":"",
"stepone.html":"(v('parry') && v('query')) ? 0 : 1",
"springsprung.html":"",
"spelt.html":"",
"speech.html":"(v('5worldsedge') && v('boat')) ? 2 : ((v('suit') && v('boat')) ? 1 : (v('eyes') ? 0 : 3))",
"sosinkstheday-star.html":"",
"sorrows.html":"v('eveningstar') ? 0 : 1",
"soon.html":"",
"son_2.html":"",
"son_1.html":"",
"songs.html":"v('autumnalwalkings') ? 1 : (v('2timesgeometry') ? 3 : (v('1calliopeatmarathon') ? 2 : 0))",
"sonata.html":"(v('node')) ? (v('transformation') ? 0 : 2) : 1",
"son.html":"",
"sometimesdawn.html":"",
"somesay.html":"",
"somefalseleads.html":"",
"soiwroteacolumn.html":"",
"sleepysong.html":"(v('sonata') && v('boat')) ? 1 : 0",
"sleepy.html":"(v('drowsy') && !v('there')) ? 1 : (v('drowsy') && v('there') ? 2 : 0)",
"six.html":"",
"shid.html":"",
"shadowhappiness.html":"(v('sonata') && v('sleepy') && v('songs')) ? 1 :           (v('sonata') && !v('sleepy')) ? 3 : (v('sonata') && v('sleepy') ? 2 : (v('sonata')  ? 0 : 4))",
"severity.html":"(v('scent') && !v('courses')) ? 1 : (v('transubstantiate') ? 0 : 2)",
"seven.html":"",
"servicemarks.html":"v('towersinair') ? 0 : 1",
"september.html":"v('laundrydoneBeautiful')  ? 3 : (v('autumnalwalkings')  ? 2 : (v('History')  ? 1 : 0))",
"seizethedj.html":"",
"seeside.html":"",
"seesee.html":"",
"secondekphrastic.html":"",
"seaside.html":"",
"seas.html":"",
"scrimshawsalibi.html":"",
"scrimshaw.html":"",
"scent.html":"",
"savaissabrett.html":"",
"sam.html":"",
"saltorchopinin6.html":"('riddleman') ? 1 : 0",
"roundususuallsuspects.html":"",
"river.html":"",
"riding.html":"",
"riddle.html":"(v('fidelity')) ? (v('fidelity') && v('transubstantiate') ? 0 : 1) : 1",
"rest-s.html":"",
"repaying.html":"",
"reineofhearts.html":"",
"reignsinadrytime.html":"",
"realm.html":"(v('notsomuch') && v('mars')) ? 1 : (v('electric') ? 2 : 0)",
"readingstoryspaces.html":"",
"query.html":"",
"q.html":"",
"protector.html":"",
"protagonistes.html":"",
"prospects.html":"v('eveningstar') ? 0 : 1",
"prophet.html":"v('riddle') ? 2 : (v('riddle') ? 1 : 0)",
"postcardtoher.html":"v('transformation') ? 2 : (!v('sonata') ? 1 : (!v('greyday')  && !v('endone') ? 3 : 0))",
"portraitoftheartist.html":"v('towhatend') ? 1 : 0",
"pleasures.html":"v('pasadena') ? 1 : 0",
"pleasantlake.html":"",
"pianos.html":"",
"piano.html":"",
"phantom.html":"",
"phaedrus.html":"v('stepone') && v('ikons') ? 1 : (v('stepone') && !v('ikons') ? 2 : 0)",
"passages.html":"",
"pasadena.html":"v('myfathersroom') ? 0 : 1",
"partfour.html":"",
"parry.html":"",
"parable.html":"",
"pandoralaura.html":"",
"outofrhythm.html":"v('songs') && !v('river') ? 2 : (v('songs') ? 3 : (v('songs') ? 0 : 1))",
"outofmemory.html":"",
"outerspace.html":"",
"ourstorysofar.html":"rl([0.200, 0.200, 0.100, 0.100, 0.050, 0.050, 0.050, 0.050, 0.050, 0.050, 0.050, 0.050])",
"ours.html":"v('birdsweave') ? 1 : 0",
"oulipo.html":"v('backstory') ? 1 : 0",
"oreallyo.html":"",
"operatingsystem.html":"",
"onpineneedles.html":"",
"ohbravenewworld.html":"",
"occidental.html":"",
"observatory.html":"",
"obieswathed.html":"rl([0.5, 0.5])",
"obiesmouth-truth.html":"",
"nuclearfishing.html":"",
"nousnote.html":"",
"notsomuch.html":"(v('nightswork')  && v('river')) ? (v('scent')  && v('sorrows') ? 3 :1) : (v('river') ? 2 : 0)",
"notes.html":"",
"noons.html":"",
"noonecared.html":"",
"node.html":"v('caring')  ? 1 : 0",
"nightswork.html":"",
"newday.html":"v('lesheurs') ? (v('lesheurs') ? 0 : 1) : 2",
"nearly.html":"",
"naturaleloquence.html":"",
"myself.html":"(v('reineofhearts') && v('courses')) ? 1 : 0",
"myfathersroom.html":"v('aerver') ? 0 : 1",
"multilingual.html":"",
"mouths-world.html":"",
"motherlandfathertongue.html":"",
"mother.html":"",
"morning.html":"",
"moredogons.html":"",
"modernmanandbaby.html":"",
"mickhammer.html":"",
"michaelcentury.html":"",
"michael.html":"",
"memory.html":"v('__') && v('september') ? 2 :  (v('__') ? (v('september') ? 0 : 3) : 1)",
"mechanicalquip.html":"",
"meaning.html":"v('butter') ? (v('songs') ? 0: 1): 2",
"mars.html":"rl([0.5, 0.5])",
"manofaction.html":"",
"lurchesfromitsmouth.html":"",
"looknow--obie.html":"",
"livingstill.html":"",
"littlegedditing.html":"",
"lights.html":"",
"lifeinabox.html":"",
"lettureimpalpabili.html":"",
"lesheurs.html":"",
"leeryabandonnedchild.html":"",
"laundrydonebeautiful.html":"(v('cixous') && v('6') && v('newday')) ? 1 :        (v('cixous') && v('6') ? 2 : 0)",
"lake-memory.html":"",
"lacrise.html":"",
"keywest.html":"",
"justwheretheriver.html":"",
"justus.html":"",
"justlikelife.html":"",
"ja.html":"",
"iwasntevenguiltyof.html":"",
"itistothee.html":"",
"itbeginssomewhere.html":"",
"inwhichhe.html":"",
"intimenightall.html":"(v('seven')) ?  (v('songs') ? 3 : 2)   : (v('aerver') ? 0 : 1)",
"inthehigherair.html":"v('seizethedj') ? 1 : 0",
"inthedisclosuresof.html":"",
"interrogationinterra.html":"",
"input.html":"",
"inpursuitofyo.html":"",
"inlightonlight.html":"",
"index.html":"",
"inahalf-hiddencave.html":"",
"immigranttothisshore.html":"",
"illegalthey.html":"",
"ikons.html":"",
"iknownotsees.html":"",
"idyllicthey.html":"v('dazeofthewoke') ? 1 : 0",
"ideograms.html":"v('electric') && v('river') ? 0 : 1",
"iceman.html":"",
"huh.html":"",
"howthingshappen-guns.html":"",
"howhesleeps.html":"v('obiesmouth-truth') ? 1 : (v('newday') ? 2 : 0)",
"housahoser.html":"",
"hj2.html":"",
"hj.html":"",
"history.html":"",
"hishopes.html":"",
"hi-pitchedvoices.html":"(!v('caring') ) ? (!v('sorrows') ? 2 : 1) :                     (!v('transubstantiate') ? 3 : (!v('archangel') ? 4 : (!v('mouths-world') ? 5 : 0)))",
"hewakes.html":"",
"hestirs-obie.html":"",
"here.html":"v('whetherreport') && v('1calliopeatmarathon')  ? ((v('1calliopeatmarathon') && v('outerspace')) ? 1 : (v('theend') ? 0 : (v('whetherreport') ? 2 : 0))) :0",
"heprotesteth.html":"",
"hensandchicks.html":"(v('speach')  && v('songs')) ? 1 : (v('takenbythecontinual')  && !v('suit')? 2 : 0)",
"heights.html":"",
"heatwavechangeofpace.html":"",
"heaintheavy.html":"",
"gs.html":"",
"greyday.html":"",
"goldbugs.html":"",
"gnosis.html":"",
"glennbarrett.html":"",
"ghislaineguertin.html":"",
"gettingitdown.html":"",
"genesis.html":"",
"garments.html":"",
"fustytu.html":"!v('whetherreport') ? 2 : (!v('transmogrifikey') ? 1 : 02)",
"freshessai.html":"",
"freewill.html":"",
"fredandbarney.html":"v('idyllicthey') ? 0 : (v('there') ? 1 : 0)",
"francoisgirards.html":"",
"fourthekphrastic.html":"",
"fourhorsemen.html":"",
"fiveelements.html":"(v('saltorchopinin6') || v('15')) ? 0 : 1",
"firstekphrastic.html":"",
"fifthekphrastic.html":"v('anotherhouse')  ? 1 : 0",
"fidelity.html":"!v('boat') ? 0 : (v('boat') && v('inwhichhe') ? 1 :  2)",
"father_1.html":"",
"father.html":"v('gnosis') ? 1 : 0",
"failus.html":"",
"eyes.html":"!v('6continental') ? 1 : (v('6continental') ? 2 : 0)",
"everyonetriesnottobe.html":"v('suit') ? 0 : 1",
"everyones.html":"v('15') && v('ours') && v('birdsweave') ? 2 : (v('our') && v('birdsweave') ? 1 : s0)",
"eveningstar.html":"rl([0.5, 0.5])",
"etcheditself.html":"",
"essencily.html":"v('gnosis') ? 0 : (v('1982') ? 1 : 2)",
"englishtextbybruce.html":"",
"endone.html":"",
"ems.html":"",
"elorgua.html":"",
"elkid.html":"",
"elf.html":"v('obieswathed') ? 0 : 1",
"electric.html":"",
"eerjordan.html":"",
"editedout.html":"",
"eddornseyes.html":"",
"echolalia.html":"",
"easewhybother.html":"",
"duringthehypertext198.html":"",
"drowsy.html":"",
"doeshenrysee.html":"",
"distanttenderness.html":"v('notsomuch') ? 0 : 1",
"dickshunairy.html":"",
"dialectic.html":"",
"dazeofthewoke.html":"v('caught') ? 1 : 0",
"dautunno.html":"",
"dateline_2.html":"",
"dateline_1.html":"",
"dateline.html":"",
"daniel.html":"",
"daniche.html":"",
"damndearbloombloor.html":"v('1955') ? 0 :  1",
"dalaiinthesky.html":"v('sleepy') ? 1 : 0",
"crossexamination.html":"",
"credits.html":"",
"courting.html":"",
"courses.html":"(v('twos.html') && v('eveningstar.html')  && v('scent.html')) ? 1 : (v('twos.htm   l') && !v('scent.html')  ? 2 : (!v('twos.html') ? 2 : 0))",
"couplet_1.html":"v('nightswork') && v('johan') ? 2 :  (v('letter2') ? (v('johan') ? 0 :  3) :  1)",
"couplet.html":"",
"cosifantutte.html":"(!v('seven') || v('mars') && v('twom')) ? 1 : 0",
"concealedbirds.html":"",
"command_3.html":"",
"command_2.html":"",
"command_1b.html":"",
"command_1.html":"",
"command_002.html":"v('idyllicthey') ? 1 : 0",
"command_001.html":"",
"command004.html":"",
"command003.html":"",
"command.html":"",
"comingtowriting.html":"",
"cixous.html":"",
"chryalis.html":"",
"chronicle.html":"",
"che.html":"",
"certaincertainties.html":"",
"centmilledefacts.html":"",
"cave.html":"",
"caughtagain.html":"",
"caught.html":"",
"caught--continued.html":"v('aretreatingfigure') ? 0 : (v('reineofhearts') ? 1 : 2)",
"caring.html":"(v('eyes') && !v('september')) ? 1 : (v('september') && v('eyes') && !v('songs') ? 2 :             (v('eyes') && v('september') && v('songs') ? 3 : 0))",
"byitscover.html":"",
"butter.html":"(v('sweaters')  && !v('scent') || v('1982')) ? 1 : (v('sweaters')  && v('archangel') ? 2 : 0)",
"boytake.html":"",
"boat.html":"",
"blueboat-city.html":"",
"blue.html":"",
"blacktalk.html":"",
"birdsweave.html":"v('aloversdiscourse') ? 0 : 1",
"biomass.html":"(!v('pleasantlake') || !v('lesheurs')) ? 3 : (v('workplay') && !v('pleasantlake') ? 1 : (v('lesheurs')  ? 2 : 0))",
"belowanoldmountain.html":"",
"bazaar.html":"v('alone') ? 0 : 1",
"backstory.html":"",
"A_.html":"",
"awayout.html":"",
"autumnalwalkings.html":"",
"asylum.html":"",
"aswan.html":"v('phaedrus')  ? 1 : 0",
"asuspect.html":"",
"aspittinimage.html":"",
"asong.html":"",
"asinisteract.html":"",
"asiflightspoke.html":"",
"asasillyman.html":"",
"ariddleman.html":"",
"aretreatingfigure.html":"",
"areporterreflects.html":"",
"archangel.html":"",
"aprilewaltera.html":"",
"apositiveid.html":"v('scrimshawsalibi') ? 0 : 1",
"apoetafloat.html":"",
"aphoto.html":"",
"anthem.html":"",
"anotherhouse.html":"",
"anescaperoute.html":"",
"andwhere.html":"",
"andwatson.html":"",
"andshouldhavewonit.html":"",
"and.html":"",
"anchoringdevices.html":"",
"anaside.html":"",
"aloversdiscourse.html":"v('5worldsedge') ? 1 : 0",
"alone.html":"",
"allhumanwisdom.html":"",
"aleagueofnations.html":"",
"alaxalasalass.html":"",
"akeyquestion.html":"",
"after.html":"",
"AERVER.html":"",
"adeath.html":"v('eveningstar') ? 2 : (v('howhesleeps') ? 0 :  1)",
"actionandpassion.html":"",
"acallfrombelow.html":"",
"abeginning.html":"",
"a.html":"",
"9.html":"",
"8.html":"",
"720.html":"",
"7.html":"",
"6continental.html":"!v('caring') ? 2 : (v('caring') && !v('cave') ? 1 : (v('caring') && v('cave') ? 4 : (v('anotherhouse') ? 3 : 0)))",
"6.html":"",
"5worldsedge.html":"v('3johan')  && !v('6continental') ? 3 : (v('6continental') && !v('adeath') ? 2 :  (v('fifthekphrastic') ? 0 : 1))",
"5.html":"",
"4annam.html":"(v('aswan') && !v('5worldsedge'))  ? 2 : (v('aswan') ?  (v('birdsweave') ? 0 : 3) : 1)",
"4.html":"",
"3johan.html":"(v('4annam') && v('5worldsedge'))  ?  1 : 0",
"3.html":"",
"2timesgeometry.html":"v('3johan') && v('3') && v('4annam')  ?  2 :              (v('3johan') && v('3') && v('wonders') ? 1: 0)",
"22shortfilmsrerpower.html":"",
"2.html":"",
"1calliopeatmarathon.html":"v('3johan') && v('3') && v('4annam')  ?  1 : 0",
"1982.html":"v('scent') && !v('blueboat-city') ? 1 :  (!v('scent') ? 2 :  0)",
"1955.html":"v('biomass') ?  (!v('biomass') ? 1 : 2) : (v('biomass') && v('1982') && !v('stories') ? 3 :  0)",
"15.html":"",
"14.html":"v('towersinair') ? 0 : 1",
"13.html":"",
"12.html":"",
"11.html":"",
"10.html":"",
"1.html":"(v('songs') && v('Six') && v('eyes') && v('suit')) ? 3 :  (v('there') ? 2 : (v('there') ? 0 : 1))",
"-30-.html":"",
};

console.log("GUARDS:")

