var DICT_LEXIA_TO_PARENT_FOLDER = {
    "-30-.html": "here/History/PleasantLake/partfour/memory",
    ".html": "here/History/PleasantLake/partfour/memory",
    ".html": "here/History/PleasantLake/partfour/memory",
    ".html": "here/History/PleasantLake/partfour/memory",
    "1.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/PandoraLaura/ikons",
    "10.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/PandoraLaura/ikons",
    "11.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/PandoraLaura/ikons",
    "12.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/PandoraLaura/ikons",
    "13.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/PandoraLaura/ikons",
    "14.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/PandoraLaura/ikons",
    "15.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/PandoraLaura/ikons",
    "1955.html": "here/History/TheEndoftheColdWar",
    "1982.html": "here/History/TheEndoftheColdWar",
    "1CalliopeatMarathon.html": "here/Songs",
    "2.html": "here/History/PleasantLake/partfour/Phaedrus",
    "2.html": "here/History/PleasantLake/partfour/Phaedrus",
    "22shortfilmsreRPower.html": "here/History/TheEndoftheColdWar",
    "2Timesgeometry.html": "here/Songs",
    "3.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/PandoraLaura/ikons",
    "3Johan.html": "here/Songs",
    "4.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/PandoraLaura/ikons",
    "4AnnaM.html": "here/Songs",
    "5.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/PandoraLaura/ikons",
    "5Worldsedge.html": "here/Songs",
    "6.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/PandoraLaura/ikons",
    "6Continental.html": "here/Songs",
    "7.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/PandoraLaura/ikons",
    "720.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/Heights",
    "8.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/PandoraLaura/ikons",
    "9.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/PandoraLaura/ikons",
    "A.html": "here/History/PleasantLake/Tapes56/Scrimshaw",
    "AERVER.html": "here/inthehigherair",
    "ARiddleman.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "ActionandPassion.html": "here/History/TheEndoftheColdWar",
    "Adeath.html": "here/History/shadowhappiness/Riddle",
    "Alaxalasalass.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Chryalis",
    "Anchoringdevices.html": "here/History/PleasantLake/partfour/heprotesteth",
    "Apoetafloat.html": "here/History/PleasantLake/six",
    "AprileWalterA.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/dickshunairy",
    "Aspittinimage.html": "here/History/PleasantLake/six",
    "Aswan.html": "here/History/PleasantLake/partfour",
    "Blueboat-city.html": "here/History/PleasantLake/Itbeginssomewhere",
    "Boytake.html": "here/History/PleasantLake/Tapes56",
    "Butter.html": "here/History/TheEndoftheColdWar",
    "Byitscover.html": "here/History/PleasantLake/six",
    "Centmilledefacts.html": "here/inthehigherair",
    "Che.html": "here/History/PleasantLake/six/apositiveID",
    "Chronicle.html": "here/History/TheEndoftheColdWar/stories",
    "Chryalis.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "Cixous.html": "here/there/September",
    "Cosifantutte.html": "here/History/PleasantLake/seven",
    "CrossExamination.html": "here/History/PleasantLake/seven",
    "Dalaiinthesky.html": "here/inthehigherair/Sleepy",
    "DaniChe.html": "here/History/PleasantLake/six/apositiveID",
    "Daniel.html": "here/History/PleasantLake/six/apositiveID",
    "DoesHenrysee.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "EdDornseyes.html": "here/History/PleasantLake/Tapes56/asylum",
    "EnglishtextbyBruce.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes",
    "EveningStar.html": "here/History/PleasantLake/seven",
    "Everyonetriesnottobe.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "Father.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Chryalis/prophet/essencily",
    "Father_1.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Chryalis/prophet/essencily",
    "FrancoisGirards.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes",
    "FredandBarney.html": "here/History/PleasantLake/Tapes56",
    "Freshessai.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes",
    "Genesis.html": "here/History/PleasantLake/Tapes56",
    "GhislaineGuertin.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes",
    "GlennBarrett.html": "here/History/PleasantLake/six",
    "HJ.html": "here/History/PleasantLake/two/HJ",
    "HJ.html": "here/History/PleasantLake/two/HJ",
    "Heatwavechangeofpace.html": "here/History/PleasantLake/seven",
    "Heights.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "Hestirs-Obie.html": "here/History/PleasantLake/Itbeginssomewhere",
    "Hi-PitchedVoices.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/dautunno/cave",
    "History.html": "here",
    "HousaHoser.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "Idyllicthey.html": "here/History/PleasantLake/Tapes56",
    "Iknownotsees.html": "here/History/PleasantLake/seven/CrossExamination",
    "Itbeginssomewhere.html": "here/History/PleasantLake",
    "Itistothee.html": "here/History/PleasantLake/Tapes56",
    "Iwasntevenguiltyof.html": "here/History/PleasantLake/two/HJ",
    "Ja.html": "here/History/PleasantLake/Tapes56",
    "KeyWest.html": "here/History/PleasantLake/Tapes56/immigranttothisshore",
    "LaCrise.html": "here/History/TheEndoftheColdWar/stories",
    "Lake-memory.html": "here/History/PleasantLake/Itbeginssomewhere",
    "LaundrydoneBeautiful.html": "here/there/September",
    "LesHeurs.html": "here/History/PleasantLake/two/Newday",
    "ListaLinkow.html": "",
    "LittleGedditing.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/goldbugs",
    "Looknow--Obie.html": "here/History/PleasantLake/Itbeginssomewhere",
    "Mars.html": "here/History/PleasantLake/seven/reignsinadrytime",
    "Meaning.html": "here/History/TheEndoftheColdWar",
    "Michael.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "MichaelCentury.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes",
    "MickHammer.html": "here/History/PleasantLake/six/leeryabandonnedchild",
    "Newday.html": "here/History/PleasantLake/two",
    "Noonecared.html": "here/History/PleasantLake/two/HJ",
    "Notes.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower",
    // "Notes.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    //  "Notes.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes",
    "Obiesmouth-truth.html": "here/History/PleasantLake/two/mouths-world",
    "Obieswathed.html": "here/History/PleasantLake/two",
    "Observatory.html": "here/History/PleasantLake/seven/reignsinadrytime",
    "Ohbravenewworld.html": "here/History/PleasantLake/Tapes56",
    "PandoraLaura.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "Pasadena.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "Passages.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "Phaedrus.html": "here/History/PleasantLake/partfour",
    "PleasantLake.html": "here/History",
    "Prospects.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/SEEside",
    "Protagonistes.html": "here/History/PleasantLake/Tapes56",
    "Q.html": "here/History/PleasantLake/Tapes56/Scrimshaw",
    "ReadingStoryspaces.html": "twilight",
    "Reineofhearts.html": "here/there/September",
    "Riddle.html": "here/History/shadowhappiness",
    "River.html": "here/History/TheEndoftheColdWar",
    "Roundususuallsuspects.html": "here/History/PleasantLake/six",
    "SEEside.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes",
    "Savaissabrett.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/failus",
    "Scrimshaw.html": "here/History/PleasantLake/Tapes56",
    "Scrimshawsalibi.html": "here/History/PleasantLake/six/leeryabandonnedchild",
    "September.html": "here/there",
    "Sleepy.html": "here/inthehigherair",
    "SoIwroteacolumn.html": "here/History/PleasantLake/two/HJ",
    "Son.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Chryalis/prophet/essencily",
    "Son_1.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Chryalis/prophet/essencily",
    "Son_2.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Chryalis/prophet/essencily",
    "Songs.html": "here",
    "Sosinkstheday-star.html": "here/History/PleasantLake/seven",
    "Tapes56.html": "here/History/PleasantLake",
    "TheEndoftheColdWar.html": "here/History",
    "TheOldManandthesee.html": "here/History/PleasantLake/seven",
    "TheSailorread.html": "here/History/PleasantLake/two/HJ",
    "Thekindofmanwho.html": "here/History/PleasantLake/partfour",
    "Themeaning.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/yoda",
    "Times.html": "here/History/TheEndoftheColdWar/stories",
    "Twom.html": "here/History/PleasantLake/six/whosaidwhat",
    "Vivailpapa.html": "here/History/PleasantLake/seven/TheOldManandthesee",
    "Weoftenfelt.html": "here/noons",
    "Wheretheblacknesslaps.html": "here/History/PleasantLake/seven",
    "Whosthestoolie.html": "here/History/PleasantLake/six",
    "WolfLake.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/dautunno/cave",
    "__nousnote.html": "here/inthehigherair/AERVER",
    "aLeagueofNations.html": "here/History/PleasantLake/Tapes56",
    "abeginning.html": "here/there/anotherhouse/wonders",
    "acallfrombelow.html": "here/History/PleasantLake/two/HJ",
    "after.html": "here/History/TheEndoftheColdWar/1982",
    "akeyquestion.html": "here/History/PleasantLake/six/Aspittinimage",
    "allhumanwisdom.html": "here/History/PleasantLake/six",
    "alone.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "aloversdiscourse.html": "here/there/September/Reineofhearts/twos",
    "anaside.html": "here/History/PleasantLake/seven",
    "and.html": "here/History/PleasantLake/partfour/areporterreflects/somefalseleads/dateline_1",
    "andWatson.html": "here/History/PleasantLake/six/leeryabandonnedchild",
    "andshouldhavewonit.html": "here/inthehigherair/Sleepy",
    "andwhere.html": "here/History/PleasantLake/six/whosaidwhat",
    "anescaperoute.html": "here/History/PleasantLake/partfour/caught",
    "anotherhouse.html": "here/there",
    "anthem.html": "here/inthehigherair/Centmilledefacts",
    "aphoto.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/asong",
    "apositiveID.html": "here/History/PleasantLake/six",
    "archangel.html": "here/History/TheEndoftheColdWar",
    "areporterreflects.html": "here/History/PleasantLake/partfour",
    "aretreatingfigure.html": "here/History/PleasantLake/partfour/caught--continued",
    "asasillyman.html": "here/History/PleasantLake/partfour/portraitoftheartist",
    "asiflightspoke.html": "here/noons",
    "asinisteract.html": "here/History/PleasantLake/two/operatingsystem",
    "asong.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "asuspect.html": "here/History/PleasantLake/six/leeryabandonnedchild",
    "asylum.html": "here/History/PleasantLake/Tapes56",
    "autumnalwalkings.html": "here/there/September",
    "awayout.html": "here/History/PleasantLake/partfour/lifeinabox",
    "backstory.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes",
    "bazaar.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "belowanoldmountain.html": "here/noons",
    "biomass.html": "here/inthehigherair/AERVER",
    "birdsweave.html": "here/there/caring",
    "blacktalk.html": "here/History/PleasantLake/Tapes56",
    "blue.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/oreallyo",
    "boat.html": "here/there/September/Reineofhearts",
    "caring.html": "here/there",
    "caught--continued.html": "here/History/PleasantLake/partfour",
    "caught.html": "here/History/PleasantLake/partfour",
    "caughtagain.html": "here/History/PleasantLake/Tapes56",
    "cave.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/dautunno",
    "certaincertainties.html": "here/History/PleasantLake/partfour",
    "comingtowriting.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "command.html": "here/History/PleasantLake/partfour",
    "command.html": "here/History/PleasantLake/partfour",
    "command.html": "here/History/PleasantLake/partfour",
    "command.html": "here/History/PleasantLake/partfour",
    "command_1.html": "here/History/PleasantLake/seven",
    "command_1.html": "here/History/PleasantLake/seven",
    "command_1.html": "here/History/PleasantLake/seven",
    "concealedbirds.html": "here/noons",
    "couplet.html": "here/inthehigherair/Centmilledefacts",
    "couplet.html": "here/inthehigherair/Centmilledefacts",
    "courses.html": "here/there/September/Reineofhearts",
    "courting.html": "here/inthehigherair/Sleepy",
    "damndearBloomBloor.html": "here/inthehigherair/Centmilledefacts",
    "dateline.html": "here/History/PleasantLake/partfour/areporterreflects/somefalseleads",
    "dateline_1.html": "here/History/PleasantLake/partfour/areporterreflects/somefalseleads",
    "dateline_2.html": "here/History/PleasantLake/partfour/areporterreflects/somefalseleads",
    "dautunno.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes",
    "dazeofthewoke.html": "here/History/PleasantLake/Tapes56",
    "dialectic.html": "here/History/PleasantLake/partfour/Phaedrus",
    "dickshunairy.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "distanttenderness.html": "here/History/TheEndoftheColdWar",
    "drowsy.html": "here/inthehigherair/Sleepy",
    "duringtheHypertext198.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes",
    "easewhybother.html": "here/History/PleasantLake/six",
    "echolalia.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "editedout.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "eerJordan.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "elOrGua.html": "here/History/PleasantLake/six/apositiveID",
    "electric.html": "here/History/TheEndoftheColdWar",
    "elf.html": "here/inthehigherair/Sleepy",
    "elkid.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "ems.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/goldbugs",
    "endone.html": "here/History/PleasantLake/Itbeginssomewhere",
    "essencily.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Chryalis/prophet",
    "etcheditself.html": "here/noons",
    "everyones.html": "here/there/caring",
    "eyes.html": "here/inthehigherair/Centmilledefacts",
    "eyes.html": "here/inthehigherair/Centmilledefacts",
    "failus.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes",
    "fidelity.html": "here/History/shadowhappiness",
    "fifthekphrastic.html": "here/inthehigherair/AERVER/biomass",
    "firstekphrastic.html": "here/inthehigherair/AERVER/biomass",
    "fiveelements.html": "here/History/TheEndoftheColdWar",
    "fourhorsemen.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes",
    "fourthekphrastic.html": "here/inthehigherair/AERVER/biomass",
    "freewill.html": "here/History/PleasantLake/seven/command_1",
    "fustytu.html": "here/inthehigherair/AERVER",
    "garments.html": "here/inthehigherair/Sleepy",
    "gettingitdown.html": "here/History/PleasantLake/Tapes56/Boytake/huh",
    "gnosis.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Chryalis/prophet/essencily",
    "goldbugs.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "greyday.html": "here/History/PleasantLake/Itbeginssomewhere",
    "gs.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/goldbugs",
    "heaintheavy.html": "here/History/PleasantLake/six",
    "hensandchicks.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "heprotesteth.html": "here/History/PleasantLake/partfour",
    "here.html": "",
    "hewakes.html": "here/History/PleasantLake/two/howhesleeps",
    "hishopes.html": "here/inthehigherair/Sleepy",
    "history.html": "here/History/PleasantLake/seven/whathappenedtous",
    "howhesleeps.html": "here/History/PleasantLake/two",
    "howthingshappen-guns.html": "here/History/PleasantLake/partfour/caught",
    "huh.html": "here/History/PleasantLake/Tapes56/Boytake",
    "iceman.html": "here/inthehigherair/Centmilledefacts",
    "ideograms.html": "here/History/TheEndoftheColdWar",
    "ikons.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/PandoraLaura",
    "illegalthey.html": "here/History/PleasantLake/Tapes56",
    "immigranttothisshore.html": "here/History/PleasantLake/Tapes56",
    "inahalf-hiddencave.html": "here/noons",
    "inbound.html": "",
    "inlightonlight.html": "here/noons",
    "inpursuitofyo.html": "here/History/PleasantLake/Tapes56",
    "input.html": "here/History/PleasantLake/two/command",
    "interrogationinterra.html": "here/History/PleasantLake/six",
    "inthedisclosuresof.html": "here/noons",
    "inthehigherair.html": "here",
    "intimenightall.html": "here/History/PleasantLake/seven/Wheretheblacknesslaps",
    "inwhichhe.html": "here/inthehigherair/Sleepy",
    "justlikelife.html": "here/History/PleasantLake/two/operatingsystem",
    "justus.html": "here/History/PleasantLake/seven/CrossExamination",
    "justwheretheriver.html": "here/noons",
    "leeryabandonnedchild.html": "here/History/PleasantLake/six",
    "lettureimpalpabili.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "lifeinabox.html": "here/History/PleasantLake/partfour",
    "lights.html": "here/History/PleasantLake/partfour",
    "livingstill.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "lurchesfromitsmouth.html": "here/noons",
    "manofaction.html": "here/History/PleasantLake/Tapes56/immigranttothisshore",
    "mechanicalquip.html": "here/History/PleasantLake/partfour/Phaedrus",
    "memory.html": "here/History/PleasantLake/partfour",
    "modernmanandbaby.html": "here/History/PleasantLake/two/Newday",
    "moredogons.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/failus/Savaissabrett",
    "morning.html": "here/inthehigherair/Centmilledefacts",
    "mother.html": "here/inthehigherair/Sleepy",
    "motherlandfathertongue.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "mouths-world.html": "here/History/PleasantLake/two",
    "multilingual.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "myfathersroom.html": "here/there/anotherhouse/wonders/abeginning",
    "myself.html": "here/there/September",
    "naturaleloquence.html": "here/History/PleasantLake/Tapes56",
    "nearly.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "nightswork.html": "here/History/PleasantLake/seven/Wheretheblacknesslaps",
    "node.html": "here/inthehigherair/AERVER",
    "noons.html": "here",
    "notsomuch.html": "here/there/September",
    "nuclearfishing.html": "here/History/PleasantLake/seven/seizetheDJ",
    "occidental.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes/oreallyo",
    "onpineneedles.html": "here/noons",
    "operatingsystem.html": "here/History/PleasantLake/two",
    "oreallyo.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "oulipo.html": "here/inthehigherair/Centmilledefacts",
    "ours.html": "here/there/caring",
    "ourstorysofar.html": "twilight",
    "outerspace.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "outofmemory.html": "here/History/PleasantLake/two",
    "outofrhythm.html": "here/History/TheEndoftheColdWar",
    "parable.html": "here/inthehigherair/Centmilledefacts",
    "parry.html": "here/History/PleasantLake/partfour/Phaedrus",
    "partfour.html": "here/History/PleasantLake",
    "phantom.html": "here/inthehigherair/Centmilledefacts",
    "piano.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Notes/Notes",
    "pianos.html": "here/inthehigherair/Centmilledefacts",
    "pleasures.html": "here/inthehigherair/Centmilledefacts",
    "portraitoftheartist.html": "here/History/PleasantLake/partfour",
    "postcardtoher.html": "here/History/PleasantLake/Itbeginssomewhere",
    "prophet.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Chryalis",
    "protector.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/Chryalis",
    "query.html": "here/History/PleasantLake/partfour/Phaedrus",
    "realm.html": "here/inthehigherair/Sleepy",
    "reignsinadrytime.html": "here/History/PleasantLake/seven",
    "repaying.html": "here/inthehigherair/Sleepy",
    "rest-s.html": "here/inthehigherair/Centmilledefacts",
    "riding.html": "here/inthehigherair/Sleepy",
    "saltorChopinin6.html": "here/History/TheEndoftheColdWar",
    "sam.html": "here/History/shadowhappiness/transubstantiate",
    "scent.html": "here/there/September/Reineofhearts",
    "seas.html": "here/History/PleasantLake/seven/CrossExamination",
    "seaside.html": "twilight/ReadingStoryspaces",
    "secondekphrastic.html": "here/inthehigherair/AERVER/biomass",
    "seesee.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "seizetheDJ.html": "here/History/PleasantLake/seven",
    "servicemarks.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "seven.html": "here/History/PleasantLake",
    "severity.html": "here/there/September/Reineofhearts",
    "shadowhappiness.html": "here/History",
    "shid.html": "here/History/PleasantLake/Tapes56/naturaleloquence",
    "six.html": "here/History/PleasantLake",
    "sleepysong.html": "here/inthehigherair/Centmilledefacts",
    "somefalseleads.html": "here/History/PleasantLake/partfour/areporterreflects",
    "somesay.html": "here/inthehigherair/Sleepy",
    "sometimesdawn.html": "here/noons",
    "sonata.html": "here/History/shadowhappiness",
    "soon.html": "here/History/PleasantLake/two/howhesleeps",
    "sorrows.html": "here/there/September/Reineofhearts",
    "speech.html": "here/there/September/Reineofhearts",
    "spelt.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "springsprung.html": "here/History/PleasantLake/Tapes56/immigranttothisshore",
    "stepone.html": "here/History/PleasantLake/partfour/Phaedrus",
    "stories.html": "here/History/TheEndoftheColdWar",
    "suit.html": "here/there/September/Reineofhearts",
    "suitcasememory.html": "here/History/PleasantLake/two/outofmemory",
    "surrender.html": "here/there/September/Reineofhearts",
    "suspicions.html": "here/there/September/Reineofhearts",
    "sweaters.html": "here/History/TheEndoftheColdWar",
    "takenbythecontinual.html": "here/inthehigherair/Centmilledefacts",
    "tegvara.html": "here/History/PleasantLake/six/apositiveID",
    "tempofuggechetassonna.html": "here/History/PleasantLake/seven/TheOldManandthesee",
    "tempsvierge.html": "here/there/September",
    "theend.html": "here/there/anotherhouse/wonders",
    "there.html": "here",
    "thetruth.html": "here/History/PleasantLake/partfour/certaincertainties",
    "thirdekphrastic.html": "here/inthehigherair/AERVER/biomass",
    "thiscomputer.html": "here/History/PleasantLake/two/command",
    "tiredofpomo.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes/spelt",
    "toher-perspective.html": "here/History/PleasantLake/Itbeginssomewhere",
    "totheleftof.html": "here/History/PleasantLake/two/HJ",
    "towersinair.html": "here/there/caring",
    "towhatend.html": "here/History/PleasantLake/partfour",
    "transformation.html": "here/History/shadowhappiness",
    "transmogrifikey.html": "here/History/PleasantLake/two/HJ",
    "transubstantiate.html": "here/History/shadowhappiness",
    "twilight.html": "",
    "two.html": "here/History/PleasantLake",
    "twos.html": "here/there/September/Reineofhearts",
    "uponoppositeshores.html": "here/noons",
    "versusthetermination.html": "here/History/PleasantLake/seven/command_1",
    "waterglinting.html": "here/noons",
	"waterglinting2.html": "root",
    "whathappenedtous.html": "here/History/PleasantLake/seven",
    "whathappens.html": "here/History/PleasantLake/partfour/caught",
    "whatsinkswhatrises.html": "here/History/PleasantLake/seven/Wheretheblacknesslaps",
    "whatthesailorsays.html": "here/History/PleasantLake/two/operatingsystem",
    "whereweeblong.html": "here/History/PleasantLake/seven/whathappenedtous",
    "whether.html": "here/inthehigherair/Centmilledefacts",
    "whetherreport.html": "here/inthehigherair/AERVER",
    "who.html": "here/History/PleasantLake/partfour/Thekindofmanwho",
    "whosaidwhat.html": "here/History/PleasantLake/six",
    "wisdom.html": "here/History/PleasantLake/partfour/Phaedrus",
    "wonders.html": "here/there/anotherhouse",
    "workplay.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "worldnoises.html": "here/History/PleasantLake/two/howhesleeps",
    "yoda.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "youllsees.html": "here/History/TheEndoftheColdWar/22shortfilmsreRPower/Notes",
    "yourstruly.html": "here/History/PleasantLake/six/interrogationinterra",
};

//find ALL keys by value from above dictionary
//zwraca wszystko to, co jest bezpoœrednio w danym folderze
function tree_search_by_value(A) {
    //
    A = A.toLowerCase();

    if (A.startsWith("/")) {//usun pierwszy /
        A = A.substring(1);
    }
    var li = []
    Object.keys(DICT_LEXIA_TO_PARENT_FOLDER).forEach(function (key) {
        let vall = DICT_LEXIA_TO_PARENT_FOLDER[key];
        vall = vall.toLowerCase();
//		console.log( key+"--->"+ vall );
        if (A == vall) {
            li.push(key);
        }
    });

    return li

}

function tree_search_by_value_accept_deep_children(A) {
    //akceptuje, gdy w sciezce gdziekolwiek znajduje sie A
    A = A.toLowerCase();
    if (A.startsWith("/")) {//usun pierwszy /
        A = A.substring(1);
    }

    var li = []
    Object.keys(DICT_LEXIA_TO_PARENT_FOLDER).forEach(function (key) {
        let vall = DICT_LEXIA_TO_PARENT_FOLDER[key];
        vall = vall.toLowerCase();


        if (vall.includes(A)) {//  czy gdziewkolwiek jest '22shortfilms/'
            li.push(key);
        }
    });

    return li

}


function FindParentPathFromFileName(filename) {
    let found = null;
    Object.keys(DICT_LEXIA_TO_PARENT_FOLDER).forEach(function (key) {
        //if(key.toLowerCase()==filename.toLowerCase()){
        if (key == filename) {
            found = DICT_LEXIA_TO_PARENT_FOLDER[key];
            return
        }
    });
    if (found == null) {
        return FindParentPathFromFileNameLOWERCASE(filename);
    }
    return found
}

function FindParentPathFromFileNameLOWERCASE(filename) {
    let found = null;
    Object.keys(DICT_LEXIA_TO_PARENT_FOLDER).forEach(function (key) {
        if (key.toLowerCase() == filename.toLowerCase()) {
            found = DICT_LEXIA_TO_PARENT_FOLDER[key];
            return
        }
    });
    if (found == null) {
    }
    return found
}



function CurrentFileName() {
    let d = document.getElementById("file_name")
    return d.innerHTML.toString();
}

//let R = tree_search_by_value('here/History/PleasantLake/Itbeginssomewhere');
//alert(R)

var CURRENT_FILE_NAME = CurrentFileName();
//console.log("CurrentFileName()="+CURRENT_FILE_NAME);

var PARENT_PATH = FindParentPathFromFileName(CurrentFileName())
//console.log("FindParentPathFromFileName()="+PARENT_PATH);

//console.log("tree_search_by_value()="+tree_search_by_value(PARENT_PATH));